<?php
if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('lastPing')) {
    function lastPing($dt) {
        $hour = 3600;
        $day = 86400;
        if ($dt <= 1) {
            return '1 second';
        } else if ($dt < 60) {
            return $dt . ' seconds';
        } else if ($dt < 90) {
            return '1 minute';
        } else if ($dt < $hour * 1.5) {
            return round((int)$dt / 60) . ' minutes';
        } else if ($dt < $day){
            return round((int)$dt / $hour) . ' hours';
        } else if ($dt < $day + 12 * $hour) {
            return '1 day';
        } else {
            return round((int)$dt / $day) . ' days';
        }
    }
}

$lastPingTime = $block['lastpingtime'];
$pingdt = time() - $lastPingTime;
$sendping = "https://dashboard.scanpay.dk/settings/api/setup?module=woocommerce&url=" . urlencode($block['pingurl']);
$instructions = 'follow the instructions in the <a target="_blank" href="https://docs.scanpay.dk/modules/woocommerce">setup guide</a>' .
                ' and test your configuration with <i><a target="_blank" href="'. $sendping . '">send ping</a></i>.';

?>

<p style="margin: 0 0 22px;">
  <a class="button button-primary" target="_blank" href="https://docs.scanpay.dk/modules/woocommerce">Setup guide</a>
  <a class="button" style="margin: 0 4px;" target="_blank" href="?page=wc-status&tab=logs">Debug logs</a>
  <a class="button" target="_blank" href="https://github.com/scanpaydk/woocommerce-scanpay">GitHub</a>
  <a class="button" style="margin: 0 4px;" target="_blank" href="<?php echo $sendping; ?>">Send ping</a>
</p>

<?php if(!$lastPingTime) : ?>
  <!-- Never received a ping -->
  <div style="background: #fff4cc; border-left: 5px solid #ffe070; padding: 10px 0 9px 15px">
    <div style="font-weight: bold; padding: 0 0 2px;">Never received any pings from Scanpay.</div>
    Please <?php echo $instructions; ?>
  </div>

<?php elseif($pingdt < 0) : ?>
  <!-- ERROR: lastPingTime is in the future -->
  <?php error_log('lastPingTime is in the future'); ?>
  <div style="background: #fad7d4; border-left: 5px solid #f08a81; padding: 10px 0 9px 15px">
    <div style="font-weight: bold; padding: 0 0 2px;">Error: lastPingTime is in the future</div>
    Something is wrong. Please contact support at <a target="_blank" href="mailto:support@scanpay.dk?Subject=Error%3A+lastPingTime+is+in+the+future">support@scanpay.dk</a>
  </div>

<?php elseif($pingdt < 600) : ?>
  <!-- Everything is perfect! -->
  <div style="background: #dff0d8; border-left: 5px solid #3c763d; padding: 10px 0 9px 15px">
    <div style="font-weight: bold; padding: 0 0 2px;">Success: Your store is synchronized with Scanpay</div>
    Last ping received <?php echo lastPing($pingdt) ?> ago. Your store will continuously receive updates through our <a target="_blank" href="https://docs.scanpay.dk/synchronization">Sync API</a>.
  </div>

<?php elseif($pingdt < 1800) : ?>
  <!-- No pings received in (10-30 mins) -->
  <div style="background: #fff7c9; border-left: 5px solid #ecd868; padding: 10px 0 9px 15px">
    <div style="font-weight: bold; padding: 0 0 2px;">Warning: Your store might be out of sync with Scanpay</div>
    <?php echo lastPing($pingdt) ?> has passed since last ping. This is quite unusual, but please just wait a few more minutes.
  </div>

<?php else : ?>
  <!-- Long time since last ping -->
  <div style="background: #ffc0c0; border-left: 5px solid #cc3e3e; padding: 10px 0 9px 15px">
    <div style="font-weight: bold; padding: 0 0 2px;">ERROR: <?php echo lastPing($pingdt) ?> since last ping!</div>
    Something is wrong. Please <?php echo $instructions; ?>
  </div>
<?php endif; ?>

